create table "public"."access_assignment_permissions" (
  "id"            bigint generated by default as identity not null,
  "assignment_id" uuid   not null,
  "resource_type" text   not null,
  "resource_key"  text   not null,
  "permission"    text   not null default 'allow',
  constraint "access_assignment_permissions_pkey" primary key ("id"),
  constraint "access_assignment_permissions_assignment_id_fkey" foreign key ("assignment_id") references public.access_assignments("id") on delete cascade
);

alter table "public"."access_assignment_permissions" enable row level security;

create index idx_access_assignment_permissions_assignment_id on public.access_assignment_permissions using btree (assignment_id);
create unique index idx_access_assignment_permissions_unique on public.access_assignment_permissions using btree (assignment_id, resource_type, resource_key);

create policy "Access assignment permissions viewable by authenticated"
  on "public"."access_assignment_permissions"
  for select
  to authenticated
  using (true);

create policy "Admins and operators insert access assignment permissions"
  on "public"."access_assignment_permissions"
  for insert
  to authenticated
  with check ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

create policy "Admins and operators update access assignment permissions"
  on "public"."access_assignment_permissions"
  for update
  to authenticated
  using ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))))
  with check ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

create policy "Admins and operators delete access assignment permissions"
  on "public"."access_assignment_permissions"
  for delete
  to authenticated
  using ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

grant select, insert, update, delete on table "public"."access_assignment_permissions" to "authenticated";
