create table "public"."access_assignment_permissions" (
  "id"                bigint generated by default as identity not null,
  "assignment_id"     uuid   not null,
  "resource_type"     text   not null,
  "permission"        text   not null default 'allow',
  "building_id"       bigint,
  "floor_id"          bigint,
  "special_access_id" bigint,
  constraint "access_assignment_permissions_pkey" primary key ("id"),
  constraint "access_assignment_permissions_assignment_id_fkey" foreign key ("assignment_id") references public.access_assignments("id") on delete cascade,
  constraint "access_assignment_permissions_floor_building_check" check (resource_type <> 'floor' or building_id is not null),
  constraint "access_assignment_permissions_floor_id_fkey" foreign key ("floor_id") references public.floors("id") on delete cascade,
  constraint "access_assignment_permissions_special_access_id_fkey" foreign key ("special_access_id") references public.special_accesses("id") on delete cascade
);

alter table "public"."access_assignment_permissions" enable row level security;

create index idx_access_assignment_permissions_assignment_id on public.access_assignment_permissions using btree (assignment_id);
create index idx_access_assignment_permissions_building on public.access_assignment_permissions using btree (building_id);
create index idx_access_assignment_permissions_floor_id on public.access_assignment_permissions using btree (floor_id);
create index idx_access_assignment_permissions_special_access_id on public.access_assignment_permissions using btree (special_access_id);
create unique index idx_access_assignment_permissions_floor on public.access_assignment_permissions using btree (assignment_id, floor_id) where (resource_type = 'floor' and floor_id is not null);
create unique index idx_access_assignment_permissions_special on public.access_assignment_permissions using btree (assignment_id, special_access_id) where (resource_type = 'special_access' and special_access_id is not null);

create policy "Access assignment permissions viewable by authenticated"
  on "public"."access_assignment_permissions"
  for select
  to authenticated
  using (true);

create policy "Admins and operators insert access assignment permissions"
  on "public"."access_assignment_permissions"
  for insert
  to authenticated
  with check ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

create policy "Admins and operators update access assignment permissions"
  on "public"."access_assignment_permissions"
  for update
  to authenticated
  using ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))))
  with check ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

create policy "Admins and operators delete access assignment permissions"
  on "public"."access_assignment_permissions"
  for delete
  to authenticated
  using ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

grant select, insert, update, delete on table "public"."access_assignment_permissions" to "authenticated";