create table "public"."buildings" (
  "id"         bigint                   generated by default as identity not null,
  "name"       text                     not null,
  "created_at" timestamp with time zone default now(),
  "sort_order" bigint,
  constraint "buildings_name_key" unique (name),
  constraint "buildings_pkey" primary key (id)
);

alter table "public"."buildings"
  enable row level security;

create policy "Admins delete buildings" on "public"."buildings"
  for delete
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins insert buildings" on "public"."buildings"
  for insert
  to PUBLIC
  with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins update buildings" on "public"."buildings"
  for update
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Buildings viewable by everyone" on "public"."buildings"
  for select
  to PUBLIC
  using ((( select auth.role() as role) = 'authenticated'::text));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."buildings" to "authenticated", "postgres", "service_role";
