create table "public"."cardless_registry" (
  "id"                          bigint                   generated by default as identity not null,
  "person_id"                   uuid,
  "first_name"                  text,
  "last_name"                   text,
  "employee_no"                 text,
  "building_id"                 bigint,
  "dependency_id"               bigint,
  "floor"                       text,
  "reason"                      text                     not null,
  "comments"                    text,
  "recorded_at"                 timestamp with time zone default now(),
  "recorded_by"                 uuid,
  "kone_status_at_registration" boolean,
  constraint "cardless_registry_building_id_fkey" foreign key (building_id) references public.buildings(id) on delete set null,
  constraint "cardless_registry_pkey" primary key (id),
  constraint "cardless_registry_dependency_id_fkey" foreign key (dependency_id) references public.dependencies(id),
  constraint "cardless_registry_person_id_fkey" foreign key (person_id) references public.personnel(id) on delete set null,
  constraint "cardless_registry_recorded_by_fkey" foreign key (recorded_by) references public.profiles(id) on delete set null
);

alter table "public"."cardless_registry"
  enable row level security;

create index idx_cardless_registry_building_id on public.cardless_registry using btree (building_id);

create index idx_cardless_registry_dependency_id on public.cardless_registry using btree (dependency_id);

create index idx_cardless_registry_kone_status on public.cardless_registry using btree (kone_status_at_registration)
  where (kone_status_at_registration is not null);

create index idx_cardless_registry_person_id on public.cardless_registry using btree (person_id);

create index idx_cardless_registry_reason on public.cardless_registry using btree (reason);

create index idx_cardless_registry_recorded_at on public.cardless_registry using btree (recorded_at desc);

create index idx_cardless_registry_recorded_by on public.cardless_registry using btree (recorded_by);

create policy "Cardless registry deletable by operators" on "public"."cardless_registry"
  for delete
  to "authenticated"
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

create policy "Cardless registry insertable by operators" on "public"."cardless_registry"
  for insert
  to "authenticated"
  with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

create policy "Cardless registry updatable by operators" on "public"."cardless_registry"
  for update
  to "authenticated"
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

create policy "Cardless registry viewable by operators" on "public"."cardless_registry"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."cardless_registry" to "authenticated", "postgres", "service_role";

comment on column "public"."cardless_registry"."kone_status_at_registration" is 'Snapshot: TRUE si la persona tenía un ticket "Firma Responsiva" pendiente para una tarjeta KONE al momento de hacer este registro. NULL = registro manual sin person_id vinculado, o registro pre-migración sin datos suficientes.';
