create table "public"."dependencies" (
  "id"         bigint generated by default as identity not null,
  "name"       text   not null,
  "sort_order" bigint,
  constraint "dependencies_name_key" unique (name),
  constraint "dependencies_pkey" primary key (id)
);

alter table "public"."dependencies"
  enable row level security;

create policy "Admins delete dependencies" on "public"."dependencies"
  for delete
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins insert dependencies" on "public"."dependencies"
  for insert
  to PUBLIC
  with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins update dependencies" on "public"."dependencies"
  for update
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Dependencies viewable by everyone" on "public"."dependencies"
  for select
  to PUBLIC
  using ((( select auth.role() as role) = 'authenticated'::text));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."dependencies" to "authenticated", "postgres", "service_role";
