create table "public"."floors" (
  "id"          bigint generated by default as identity not null,
  "label"       text   not null,
  "sort_order"  bigint,
  "building_id" bigint,
  constraint "floors_pkey" primary key ("id"),
  constraint "floors_building_id_fkey" foreign key (building_id) references public.buildings(id)
);

alter table "public"."floors" enable row level security;

create unique index idx_floors_building_label on public.floors using btree (building_id, label);

create policy "Floors viewable by authenticated"
  on "public"."floors"
  for select
  to authenticated
  using (true);

create policy "Admins insert floors"
  on "public"."floors"
  for insert
  to authenticated
  with check ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins update floors"
  on "public"."floors"
  for update
  to authenticated
  using ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))))
  with check ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins delete floors"
  on "public"."floors"
  for delete
  to authenticated
  using ((exists ( select 1
    from public.profiles
   where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

grant select, insert, update, delete on table "public"."floors" to "authenticated";