create table "public"."history_logs" (
  "id"           bigint                   generated by default as identity not null,
  "entity_type"  text                     not null,
  "entity_id"    text,
  "entity_name"  text,
  "action"       text                     not null,
  "details"      jsonb,
  "performed_by" uuid,
  "timestamp"    timestamp with time zone default now(),
  "flow_id"      uuid,
  constraint "history_logs_performed_by_fkey" foreign key (performed_by) references auth.users(id),
  constraint "history_logs_pkey" primary key (id)
);

alter table "public"."history_logs"
  enable row level security;

create index idx_history_action on public.history_logs using btree (action);

create index idx_history_entity_id on public.history_logs using btree (entity_id);

create index idx_history_entity on public.history_logs using btree (entity_type, entity_id);

create index idx_history_logs_performed_by on public.history_logs using btree (performed_by);

create index idx_history_timestamp on public.history_logs using btree ("timestamp" desc);

create index idx_history_flow_id on public.history_logs using btree (flow_id);

create policy "Admins/Operators insert history" on "public"."history_logs"
  for insert
  to PUBLIC
  with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))));

create policy "History viewable by everyone" on "public"."history_logs"
  for select
  to PUBLIC
  using ((( select auth.role() as role) = 'authenticated'::text));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."history_logs" to "authenticated", "postgres", "service_role";
