create table "public"."migration_map" (
  "id"           bigint generated by default as identity not null,
  "source_table" text                     not null,
  "source_id"    text                     not null,
  "target_table" text                     not null,
  "target_id"    text                     not null,
  "migrated_at"  timestamp with time zone not null default now(),
  constraint "migration_map_pkey" primary key ("id"),
  constraint "migration_map_source_target_key" unique ("source_table", "source_id", "target_table")
);

alter table "public"."migration_map" enable row level security;

create policy "Migration map viewable by authenticated"
  on "public"."migration_map"
  for select
  to authenticated
  using (true);

grant select on table "public"."migration_map" to "authenticated";
