create table "public"."schedules" (
  "id"            bigint                 generated by default as identity not null,
  "name"          text                   not null,
  "days"          text[]                 not null default '{}'::text[],
  "default_entry" time without time zone,
  "default_exit"  time without time zone,
  "sort_order"    bigint,
  constraint "schedules_name_key" unique (name),
  constraint "schedules_pkey" primary key (id)
);

alter table "public"."schedules"
  enable row level security;

create policy "Admins delete schedules" on "public"."schedules"
  for delete
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins insert schedules" on "public"."schedules"
  for insert
  to PUBLIC
  with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins update schedules" on "public"."schedules"
  for update
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Schedules viewable by everyone" on "public"."schedules"
  for select
  to PUBLIC
  using ((( select auth.role() as role) = 'authenticated'::text));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."schedules" to "authenticated", "postgres", "service_role";
