create table "public"."special_accesses" (
  "id"          bigint generated by default as identity not null,
  "name"        text   not null,
  "sort_order"  bigint,
  "building_id" bigint not null,
  constraint "special_accesses_pkey" primary key (id),
  constraint "special_accesses_building_id_fkey" foreign key (building_id) references public.buildings(id)
);

create unique index special_accesses_building_name on public.special_accesses using btree (building_id, name);

alter table "public"."special_accesses"
  enable row level security;

create policy "Admins delete special" on "public"."special_accesses"
  for delete
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins insert special" on "public"."special_accesses"
  for insert
  to PUBLIC
  with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Admins update special" on "public"."special_accesses"
  for update
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Special accesses viewable by everyone" on "public"."special_accesses"
  for select
  to PUBLIC
  using ((( select auth.role() as role) = 'authenticated'::text));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."special_accesses" to "authenticated", "postgres", "service_role";
