create table "public"."tickets" (
  "id"          bigint                   generated by default as identity not null,
  "title"       text                     not null,
  "description" text,
  "type"        text                     not null,
  "priority"    text                     default 'Media'::text,
  "status"      text                     default 'pending'::text,
  "payload"     jsonb                    default '{}'::jsonb,
  "person_id"   uuid,
  "card_id"     uuid,
  "created_by"  uuid,
  "created_at"  timestamp with time zone default now(),
  constraint "tickets_card_id_fkey" foreign key (card_id) references public.cards(id) on delete cascade,
  constraint "tickets_created_by_fkey" foreign key (created_by) references auth.users(id),
  constraint "tickets_person_id_fkey" foreign key (person_id) references public.personnel(id) on delete cascade,
  constraint "tickets_pkey" primary key (id)
);

alter table "public"."tickets"
  enable row level security;

alter table "public"."tickets"
  replica identity full;

create index idx_tickets_assigned_to on public.tickets using btree (((payload ->> 'assignedTo'::text)));

create index idx_tickets_card_id on public.tickets using btree (card_id);

create index idx_tickets_created_by on public.tickets using btree (created_by);

create index idx_tickets_person_id on public.tickets using btree (person_id);

create index idx_tickets_status on public.tickets using btree (status);

create index idx_tickets_type on public.tickets using btree (type);

create policy "Admins delete tickets" on "public"."tickets"
  for delete
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = 'admin'::public.app_role)))));

create policy "Everyone insert tickets" on "public"."tickets"
  for insert
  to PUBLIC
  with check ((( SELECT auth.role() AS role) = 'authenticated'::text));

create policy "Operators update tickets" on "public"."tickets"
  for update
  to PUBLIC
  using ((exists ( select 1
   from public.profiles
  where ((profiles.id = ( select auth.uid() as uid)) AND (profiles.role = ANY (ARRAY['admin'::public.app_role, 'operator'::public.app_role]))))))
  with check (((( SELECT profiles.role
   FROM public.profiles
  WHERE (profiles.id = ( SELECT auth.uid() AS uid))) = 'admin'::public.app_role) OR (status IS DISTINCT FROM 'completed'::text)));

create policy "Tickets viewable by everyone" on "public"."tickets"
  for select
  to PUBLIC
  using ((( select auth.role() as role) = 'authenticated'::text));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."tickets" to "authenticated", "postgres", "service_role";
