-- Tabla para registro de personal sin tarjeta
-- Ejecutar en el SQL Editor de Supabase (como postgres)
-- Después, opcional: scripts/verify_cardless_registry.sql
--   recorded_by_refs_profiles debe ser true
--   recorded_by_still_refs_auth_users debe ser false

CREATE TABLE IF NOT EXISTS "public"."cardless_registry" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "person_id" uuid,
    "first_name" "text",
    "last_name" "text",
    "employee_no" "text",
    "building_id" bigint,
    "dependency_id" bigint,
    "floor" "text",
    "reason" "text" NOT NULL,
    "comments" "text",
    "recorded_at" timestamp with time zone DEFAULT "now"(),
    -- FK a profiles (no auth.users) para que PostgREST pueda hacer embed: profiles(full_name)
    "recorded_by" uuid
);

ALTER TABLE "public"."cardless_registry" OWNER TO "postgres";

-- Foreign keys (idempotente)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'cardless_registry_person_id_fkey'
    ) THEN
        ALTER TABLE ONLY "public"."cardless_registry"
            ADD CONSTRAINT "cardless_registry_person_id_fkey"
            FOREIGN KEY ("person_id") REFERENCES "public"."personnel"("id") ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'cardless_registry_building_id_fkey'
    ) THEN
        ALTER TABLE ONLY "public"."cardless_registry"
            ADD CONSTRAINT "cardless_registry_building_id_fkey"
            FOREIGN KEY ("building_id") REFERENCES "public"."buildings"("id") ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'cardless_registry_dependency_id_fkey'
    ) THEN
        ALTER TABLE ONLY "public"."cardless_registry"
            ADD CONSTRAINT "cardless_registry_dependency_id_fkey"
            FOREIGN KEY ("dependency_id") REFERENCES "public"."dependencies"("id");
    END IF;

    -- Quitar FK a auth.users si existía (rompe el embed de profiles en el cliente)
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'cardless_registry_recorded_by_fkey'
    ) THEN
        ALTER TABLE ONLY "public"."cardless_registry"
            DROP CONSTRAINT "cardless_registry_recorded_by_fkey";
    END IF;

    ALTER TABLE ONLY "public"."cardless_registry"
        ADD CONSTRAINT "cardless_registry_recorded_by_fkey"
        FOREIGN KEY ("recorded_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;
END $$;

-- Índices
CREATE INDEX IF NOT EXISTS "idx_cardless_registry_person_id" ON "public"."cardless_registry" USING "btree" ("person_id");
CREATE INDEX IF NOT EXISTS "idx_cardless_registry_recorded_at" ON "public"."cardless_registry" USING "btree" ("recorded_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_cardless_registry_building_id" ON "public"."cardless_registry" USING "btree" ("building_id");
CREATE INDEX IF NOT EXISTS "idx_cardless_registry_dependency_id" ON "public"."cardless_registry" USING "btree" ("dependency_id");
CREATE INDEX IF NOT EXISTS "idx_cardless_registry_reason" ON "public"."cardless_registry" USING "btree" ("reason");

-- Permisos (requeridos para la Data API de Supabase)
GRANT ALL ON TABLE "public"."cardless_registry" TO "anon";
GRANT ALL ON TABLE "public"."cardless_registry" TO "authenticated";
GRANT ALL ON TABLE "public"."cardless_registry" TO "service_role";

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'S' AND c.relname = 'cardless_registry_id_seq' AND n.nspname = 'public'
    ) THEN
        GRANT USAGE, SELECT ON SEQUENCE "public"."cardless_registry_id_seq" TO "anon";
        GRANT USAGE, SELECT ON SEQUENCE "public"."cardless_registry_id_seq" TO "authenticated";
        GRANT USAGE, SELECT ON SEQUENCE "public"."cardless_registry_id_seq" TO "service_role";
    END IF;
END $$;

-- RLS
ALTER TABLE "public"."cardless_registry" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Cardless registry viewable by operators" ON "public"."cardless_registry";
DROP POLICY IF EXISTS "Cardless registry insertable by operators" ON "public"."cardless_registry";
DROP POLICY IF EXISTS "Cardless registry updatable by operators" ON "public"."cardless_registry";
DROP POLICY IF EXISTS "Cardless registry deletable by operators" ON "public"."cardless_registry";

CREATE POLICY "Cardless registry viewable by operators" ON "public"."cardless_registry"
    FOR SELECT TO authenticated
    USING ((EXISTS (
        SELECT 1
        FROM "public"."profiles"
        WHERE (
            ("profiles"."id" = (SELECT "auth"."uid"() AS "uid"))
            AND ("profiles"."role" = ANY (ARRAY['admin'::"public"."app_role", 'operator'::"public"."app_role"]))
        )
    )));

CREATE POLICY "Cardless registry insertable by operators" ON "public"."cardless_registry"
    FOR INSERT TO authenticated
    WITH CHECK ((EXISTS (
        SELECT 1
        FROM "public"."profiles"
        WHERE (
            ("profiles"."id" = (SELECT "auth"."uid"() AS "uid"))
            AND ("profiles"."role" = ANY (ARRAY['admin'::"public"."app_role", 'operator'::"public"."app_role"]))
        )
    )));

CREATE POLICY "Cardless registry updatable by operators" ON "public"."cardless_registry"
    FOR UPDATE TO authenticated
    USING ((EXISTS (
        SELECT 1
        FROM "public"."profiles"
        WHERE (
            ("profiles"."id" = (SELECT "auth"."uid"() AS "uid"))
            AND ("profiles"."role" = ANY (ARRAY['admin'::"public"."app_role", 'operator'::"public"."app_role"]))
        )
    )));

CREATE POLICY "Cardless registry deletable by operators" ON "public"."cardless_registry"
    FOR DELETE TO authenticated
    USING ((EXISTS (
        SELECT 1
        FROM "public"."profiles"
        WHERE (
            ("profiles"."id" = (SELECT "auth"."uid"() AS "uid"))
            AND ("profiles"."role" = ANY (ARRAY['admin'::"public"."app_role", 'operator'::"public"."app_role"]))
        )
    )));
