-- ==============================================================================
-- NEXA: DATABASE RESET SCRIPT 
-- WARNING: THIS WILL WIPE ALL DATA AND RECREATE THE SCHEMA
-- Includes:
-- 1. Optimized RLS Policies (Performance + Security)
-- 2. Secured Functions (search_path)
-- 3. Latest Schema Definitions
-- ==============================================================================

-- 1. CLEANUP (DROP EVERYTHING)
DROP TABLE IF EXISTS history_logs CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS signed_responsivas CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS personnel CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS special_accesses CASCADE;
DROP TABLE IF EXISTS dependencies CASCADE;
DROP TABLE IF EXISTS buildings CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

DROP TYPE IF EXISTS public.app_role CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user CASCADE;

-- 2. ENUMS & TYPES
CREATE TYPE public.app_role AS ENUM ('admin', 'operator', 'viewer');

-- 3. TABLE DEFINITIONS

-- Profiles (extends auth.users)
CREATE TABLE profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE,
    full_name TEXT,
    role public.app_role DEFAULT 'viewer' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    avatar_url TEXT
);

-- Catalogs
CREATE TABLE buildings (
    id bigint generated by default as identity primary key,
    name text not null,
    floors text[] not null default '{}',
    created_at timestamp with time zone default now()
);

CREATE TABLE dependencies (
    id bigint generated by default as identity primary key,
    name text not null
);

CREATE TABLE special_accesses (
    id bigint generated by default as identity primary key,
    name text not null
);

CREATE TABLE schedules (
    id bigint generated by default as identity primary key,
    name text not null,
    days text[] not null default '{}',
    default_entry time,
    default_exit time
);

-- Personnel
CREATE TABLE personnel (
    id uuid default gen_random_uuid() primary key,
    first_name text not null,
    last_name text not null,
    employee_no text unique not null,
    area text,
    position text,
    dependency_id bigint references dependencies(id),
    building_id bigint references buildings(id),
    floor text,
    floors_required text[],
    schedule_id bigint references schedules(id),
    entry_time time,
    exit_time time,
    special_accesses text[] default '{}',
    status text default 'active',
    photo_url text, 
    created_at timestamp with time zone default now()
);

-- Cards (Unique Folio + Type)
CREATE TABLE cards (
    id uuid default gen_random_uuid() primary key,
    folio text not null,
    type text not null, -- 'P2000' or 'KONE'
    status text default 'available', -- 'available', 'active', 'blocked'
    responsiva_status text default 'unsigned', -- 'unsigned', 'signed'
    programming_status text default 'pending', -- 'pending', 'done'
    person_id uuid references personnel(id) on delete set null,
    updated_at timestamp with time zone default now(),
    UNIQUE(folio, type)
);

-- Signed Responsivas
CREATE TABLE signed_responsivas (
    id uuid default gen_random_uuid() primary key,
    person_id uuid references personnel(id) on delete cascade,
    folio text not null,
    card_type text not null,
    data jsonb not null,
    signature text not null, -- Base64 Signature
    legal_hash text,
    legal_snapshot text,
    created_at timestamp with time zone default now()
);

-- Tickets
CREATE TABLE tickets (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    type text not null,
    priority text default 'Media',
    status text default 'pending', -- 'pending', 'approved', 'rejected', 'completed'
    payload jsonb default '{}'::jsonb,
    person_id uuid references personnel(id) on delete cascade,
    card_id uuid references cards(id) on delete cascade,
    created_by uuid references auth.users(id),
    created_at timestamp with time zone default now()
);

-- History Logs (Polymorphic)
CREATE TABLE history_logs (
    id bigint generated by default as identity primary key,
    entity_type text not null, 
    entity_id text,
    action text not null,
    details jsonb,
    performed_by uuid references auth.users(id),
    timestamp timestamp with time zone default now()
);

-- 4. FUNCTIONS & TRIGGERS

-- Secure Function: handle_new_user (with explicit search_path)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, role)
    VALUES (
        NEW.id, 
        NEW.email, 
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
        'viewer'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. OPTIMIZED RLS POLICIES

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE buildings ENABLE ROW LEVEL SECURITY;
ALTER TABLE dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE special_accesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE personnel ENABLE ROW LEVEL SECURITY;
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE history_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE signed_responsivas ENABLE ROW LEVEL SECURITY;

-- Note: We wrap auth functions in (SELECT ...) for performance optimization

-- PROFILES
CREATE POLICY "Profiles viewable by everyone" ON profiles FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Admins update all profiles" ON profiles FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));

-- PERSONNEL
CREATE POLICY "Personnel viewable by everyone" ON personnel FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Admins/Operators insert personnel" ON personnel FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator')));
CREATE POLICY "Admins/Operators update personnel" ON personnel FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator')));
CREATE POLICY "Admins/Operators delete personnel" ON personnel FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator')));

-- CARDS
CREATE POLICY "Cards viewable by everyone" ON cards FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Admins/Operators insert cards" ON cards FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator')));
CREATE POLICY "Admins/Operators update cards" ON cards FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator')));
CREATE POLICY "Admins/Operators delete cards" ON cards FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator')));

-- TICKETS
CREATE POLICY "Tickets viewable by everyone" ON tickets FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Everyone insert tickets" ON tickets FOR INSERT WITH CHECK ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Operators update tickets" ON tickets FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator'))) WITH CHECK ((SELECT role FROM profiles WHERE id = (SELECT auth.uid())) = 'admin' OR (status IS DISTINCT FROM 'completed'));
CREATE POLICY "Admins delete tickets" ON tickets FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));

-- HISTORY
CREATE POLICY "History viewable by everyone" ON history_logs FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Admins/Operators insert history" ON history_logs FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator')));

-- CATALOGS (Buildings, Dependencies, Schedules, Special Accesses)
-- Buildings
CREATE POLICY "Buildings viewable by everyone" ON buildings FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Admins insert buildings" ON buildings FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins update buildings" ON buildings FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins delete buildings" ON buildings FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));

-- Dependencies
CREATE POLICY "Dependencies viewable by everyone" ON dependencies FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Admins insert dependencies" ON dependencies FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins update dependencies" ON dependencies FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins delete dependencies" ON dependencies FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));

-- Schedules
CREATE POLICY "Schedules viewable by everyone" ON schedules FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Admins insert schedules" ON schedules FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins update schedules" ON schedules FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins delete schedules" ON schedules FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));

-- Special Accesses
CREATE POLICY "Special accesses viewable by everyone" ON special_accesses FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Admins insert special" ON special_accesses FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins update special" ON special_accesses FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins delete special" ON special_accesses FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));

-- Signed Responsivas
CREATE POLICY "Responsivas viewable" ON signed_responsivas FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Admins/Operators insert responsivas" ON signed_responsivas FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator')));
CREATE POLICY "Admins/Operators delete responsivas" ON signed_responsivas FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role IN ('admin', 'operator')));

-- 6. SEED DATA
-- Catálogos
INSERT INTO buildings (name, floors) VALUES 
('Torre Administrativa', '{"S1","S2","PB","P1","P2","P3","P4","P5"}'),
('Palacio de Gobierno', '{"PB","P1","P2"}');

INSERT INTO dependencies (name) VALUES 
('Secretaría de Finanzas'), 
('Secretaría de Educación'), 
('Dirección de Tecnologías');

INSERT INTO special_accesses (name) VALUES 
('Comedores'), 
('Estacionamiento VIP'), 
('Archivo General');

INSERT INTO schedules (name, days, default_entry, default_exit) VALUES 
('Administrativo', '{"Lunes","Martes","Miércoles","Jueves","Viernes"}', '08:00:00', '16:00:00'),
('Seguridad 24/7', '{"Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"}', '00:00:00', '23:59:59');

