-- ==========================================
-- 1. LIMPIEZA TOTAL (BORRADO DE TABLAS)
-- ==========================================
-- El orden es importante por las claves foráneas
DROP TABLE IF EXISTS history_logs CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS signed_responsivas CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS personnel CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS special_accesses CASCADE;
DROP TABLE IF EXISTS dependencies CASCADE;
DROP TABLE IF EXISTS buildings CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- ==========================================
-- 2. CREACIÓN DE ESTRUCTURA (ESQUEMA ACTUAL)
-- ==========================================

-- Catálogos
CREATE TABLE buildings (
    id bigint generated by default as identity primary key,
    name text not null,
    floors text[] not null default '{}',
    created_at timestamp with time zone default now()
);

CREATE TABLE dependencies (
    id bigint generated by default as identity primary key,
    name text not null
);

CREATE TABLE special_accesses (
    id bigint generated by default as identity primary key,
    name text not null
);

CREATE TABLE schedules (
    id bigint generated by default as identity primary key,
    name text not null,
    days text[] not null default '{}',
    default_entry time,
    default_exit time
);

-- Personal
CREATE TABLE personnel (
    id uuid default gen_random_uuid() primary key,
    first_name text not null,
    last_name text not null,
    employee_no text unique not null,
    area text,
    position text,
    dependency_id bigint references dependencies(id),
    building_id bigint references buildings(id),
    floor text,
    floors_required text[],
    schedule_id bigint references schedules(id),
    entry_time time,
    exit_time time,
    special_accesses text[] default '{}',
    status text default 'active',
    photo_url text, -- Para subida de imágenes
    created_at timestamp with time zone default now()
);

-- Tarjetas (Con restricción única de Folio + Tipo)
CREATE TABLE cards (
    id uuid default gen_random_uuid() primary key,
    folio text not null,
    type text not null, -- 'P2000' o 'KONE'
    status text default 'available', -- 'available', 'active', 'blocked'
    responsiva_status text default 'unsigned', -- 'unsigned', 'signed'
    programming_status text default 'pending', -- 'pending', 'done'
    person_id uuid references personnel(id) on delete set null,
    updated_at timestamp with time zone default now(),
    UNIQUE(folio, type)
);

-- Responsivas Firmadas (Persistencia de datos + Firma)
CREATE TABLE signed_responsivas (
    id uuid default gen_random_uuid() primary key,
    person_id uuid references personnel(id) on delete cascade,
    folio text not null,
    card_type text not null,
    data jsonb not null,
    signature text not null, -- Firma en Base64
    created_at timestamp with time zone default now()
);

-- Tickets (Flujo de aprobación y pendientes sistema)
CREATE TABLE tickets (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    type text not null, -- 'Firma Responsiva', 'Programación de Acceso', 'Edición de Perfil', etc.
    priority text default 'Media',
    status text default 'pending', -- 'pending', 'approved', 'rejected'
    payload jsonb default '{}'::jsonb,
    person_id uuid references personnel(id) on delete cascade,
    card_id uuid references cards(id) on delete cascade,
    created_by uuid references auth.users(id),
    created_at timestamp with time zone default now()
);

-- Historial Polimórfico
CREATE TABLE history_logs (
    id bigint generated by default as identity primary key,
    entity_type text not null, -- 'PERSONNEL', 'CARD', 'TICKET', 'SYSTEM'
    entity_id text,
    action text not null,
    details jsonb,
    performed_by uuid references auth.users(id),
    timestamp timestamp with time zone default now()
);

-- Perfiles de Usuario (Auth)
CREATE TABLE profiles (
    id uuid references auth.users(id) on delete cascade primary key,
    full_name text,
    role text default 'user',
    avatar_url text
);

-- ==========================================
-- 3. CONFIGURACIÓN DE SEGURIDAD (RLS)
-- ==========================================
ALTER TABLE buildings ENABLE ROW LEVEL SECURITY;
ALTER TABLE dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE special_accesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE personnel ENABLE ROW LEVEL SECURITY;
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE history_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE signed_responsivas ENABLE ROW LEVEL SECURITY;

-- Políticas Simplificadas para Nexa (Acceso total autenticado/anónimo para desarrollo)
-- En producción estas deben ser más restrictivas basadas en profiles.role
CREATE POLICY "Full access" ON buildings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON dependencies FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON special_accesses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON schedules FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON personnel FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON cards FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON tickets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON history_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full access" ON signed_responsivas FOR ALL USING (true) WITH CHECK (true);

-- ==========================================
-- 4. DATOS DUMMY (SEEDS)
-- ==========================================

-- Catálogos
INSERT INTO buildings (name, floors) VALUES 
('Torre Administrativa', '{"S1","S2","PB","P1","P2","P3","P4","P5"}'),
('Palacio de Gobierno', '{"PB","P1","P2"}');

INSERT INTO dependencies (name) VALUES 
('Secretaría de Finanzas'), 
('Secretaría de Educación'), 
('Dirección de Tecnologías');

INSERT INTO special_accesses (name) VALUES 
('Comedores'), 
('Estacionamiento VIP'), 
('Archivo General');

INSERT INTO schedules (name, days, default_entry, default_exit) VALUES 
('Administrativo', '{"Lunes","Martes","Miércoles","Jueves","Viernes"}', '08:00:00', '16:00:00'),
('Seguridad 24/7', '{"Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"}', '00:00:00', '23:59:59');

-- Personal (Sin cards inicialmente para disparar tickets)
INSERT INTO personnel (first_name, last_name, employee_no, area, position, dependency_id, building_id, floor, status) VALUES 
('Juan', 'Pérez', 'EMP101', 'Soporte Técnico', 'Analista', 3, 1, 'P2', 'active'),
('Ana', 'García', 'EMP102', 'Nóminas', 'Coordinadora', 1, 1, 'P1', 'active'),
('Carlos', 'López', 'EMP103', 'Rectoría', 'Director', 2, 2, 'P2', 'active');

-- Tarjetas Disponibles
INSERT INTO cards (folio, type, status) VALUES 
('A1001', 'P2000', 'available'),
('A1002', 'P2000', 'available'),
('K5001', 'KONE', 'available'),
('K5002', 'KONE', 'available');

-- Asignar una tarjeta a Juan Pérez para probar flujo
UPDATE cards SET person_id = (SELECT id FROM personnel WHERE employee_no = 'EMP101'), status = 'active', responsiva_status = 'signed', programming_status = 'done' 
WHERE folio = 'A1001';

-- Crear algunos logs iniciales
INSERT INTO history_logs (entity_type, entity_id, action, details) VALUES 
('SYSTEM', '0', 'DB_INIT', '{"message": "Base de datos inicializada con datos dummy"}'),
('PERSONNEL', (SELECT id::text FROM personnel WHERE employee_no = 'EMP101'), 'CREATE', '{"message": "Usuario Juan Pérez creado"}');
